### ISSUE TITLE
Full path to the file?

### ISSUE THREAD

**Issue by Xhonor** [EricZimmerman/Prefetch#1]
Hello. Already asked a question on StackOverflow https://stackoverflow.com/questions/54737510/prefetch-parsing-unknown-volume-disk?noredirect=1#comment96261324_54737510 , but could not get an answer. Can you help me with this question?
How to get the full path to the file that is used in Prefetch?

**Comment by EricZimmerman** [comment]
hi

ill answer there too, but:

It should be in mounted devices and mount points. It's the storage volume guid

the full path to the file executed is in the Files referenced collection.

dump a pf file with pecmd from the command line then look for the file entry in yellow

thats the full path

**Comment by Xhonor** [comment]
I tried, but he gives me an unknown Volume ID. There is no such thing in the lists of my disks.

![image](https://user-images.githubusercontent.com/15837839/52973112-b59c3d00-33c5-11e9-8257-8083ce602e63.png)

![image](https://user-images.githubusercontent.com/15837839/52973176-e54b4500-33c5-11e9-98bd-c1e604df652f.png)

**Comment by EricZimmerman** [comment]
which entry in mountpoints is for the c drive? perhaps the guid is rearranged?

could the data you are seeing be from a previous windows install that had older GUIDs?

how old is the prefetch? has a windows10 update happened since then?

do some testing on a clean install. run an exe from somewhere, look at prefetch guid, and match it up to what is in current moutpoints.

its hard to be more specific without more details

**Comment by Xhonor** [comment]
![image](https://user-images.githubusercontent.com/15837839/52973594-33ad1380-33c7-11e9-9ac6-575a3ee88f53.png)

Noup, i start Cinema 4d - 4 hours ago...
Try in another PC.

**Comment by EricZimmerman** [comment]
try this

PS C:\WINDOWS\system32> diskpart

Microsoft DiskPart version 10.0.17763.1

Copyright (C) Microsoft Corporation.
On computer: DESKTOP-9L1HKC9

DISKPART> list disk

  Disk ###  Status         Size     Free     Dyn  Gpt
  --------  -------------  -------  -------  ---  ---
  Disk 0    Online          476 GB  2048 KB        *

DISKPART> select disk 0

Disk 0 is now the selected disk.

DISKPART> uniqueid disk

Disk ID: {5F589409-D1DC-4E18-A0D9-5A1593F78A08}

what does your C drive disk show?

**Comment by EricZimmerman** [comment]
also you may need to pull the GUID out of the binary data in mounteddevices

![image](https://user-images.githubusercontent.com/4265254/52974020-1d369600-338e-11e9-96c5-398ff5e39643.png)

please let me know what you find.

**Comment by Xhonor** [comment]
![image](https://user-images.githubusercontent.com/15837839/52975283-97d2d600-33cd-11e9-9a6e-690d59f32ee5.png)

**Comment by Xhonor** [comment]
Disk ID: C9514D29

**Comment by Xhonor** [comment]
Another disk  {1A672A06-D975-42B9-A5FC-19805A188576}

**Comment by Xhonor** [comment]
Same problem in another PC. Unknown Volume.

**Comment by EricZimmerman** [comment]
you can see the full path to the exe. that should only exist on a single drive in your case with a reference to program files, etc. that should help to a degree to determine which volume its on

**Comment by EricZimmerman** [comment]
The volume id is two parts

Creation time of the volume as a 64 bit filetime, as hex, in big endian format
The volume serial number

It's not found anywhere else that I know of.

**Comment by jasonexe2000** [comment]
I have the same issue.
Output is not in the correct GUID format.

![image](https://github.com/EricZimmerman/Prefetch/assets/5953419/4b43f88e-a24a-4074-b914-adbd5a2b4863)

**Comment by EricZimmerman** [comment]
You are incorrect assuming it's a guid. 

The format is correct. It was reversed after the initial comments long ago. 

This is not an issue. It's just the way it is.
