### ISSUE TITLE
Wrong parsing of  new runcount format of 30 version

### ISSUE THREAD

**Issue by 0xMuhannad** [EricZimmerman/Prefetch#5]
Hi eric, 

In the mid of the development of my Rust parser for Prefetch I was using your code result as a baseline for my parser's result. When I was trying to parse a version 30 prefetch with the new run count format (OFFSET 116) I found the runcount result is not parsed correctly and sometimes I get runcount as 0 in your parser.  

As shown below the run count is 3 and it should be 4. 
![image](https://github.com/EricZimmerman/Prefetch/assets/127749301/ccb78aa9-d081-4bb5-8432-6b8dc46370d1)

Also below, the run count is 0 and its not correct. 
![image](https://github.com/EricZimmerman/Prefetch/assets/127749301/f6a27437-0858-4128-9a34-7c993b81646d)

**Comment by EricZimmerman** [comment]
You aren't even using the current version of the software. Update and try again
